### ISSUE TITLE
CSS file

### ISSUE THREAD

**Issue by niutech** [sveltecult/franken-ui#1]
Could you provide a CSS file to add as a stylesheet to a static HTML web page, so I can use pure CSS version, without JS nor npm? Thanks!

**Comment by muradbu** [comment]
It's a bit extra work but you can use the [Tailwind standalone cli](https://tailwindcss.com/blog/standalone-cli) to generate the css file with the classes used in this project.

**Comment by niutech** [comment]
Thanks, but how to use it with Franken UI?

**Comment by sveltecult** [comment]
You can try grabbing the css file on the docs website
[_slug_.DdNKfqpT.zip](https://github.com/sveltecult/franken-ui/files/15069532/_slug_.DdNKfqpT.zip)

But this might get outdated soon.
