### ISSUE TITLE
Website rendering of Geist 600/700-weight font is a bit rough

### ISSUE THREAD

**Issue by hooch** [sveltecult/franken-ui#5]
The demo [here](https://www.franken-ui.dev) uses the Geist font without loading a bold version of the font, and then proceeds to apply `font-weight: bold` to the heading text.

This generates a poorly rendered bold font.

**Comment by sveltecult** [comment]
A screenshot would be nice. The docs uses variable font which I believe do not need to load a bunch of font weights. Please be specific on what device and browser are you using. Those can help fix the problem.

**Comment by hooch** [comment]
Here's a screenshot comparing Vercel's use of the font.  When I disable the `font-synthesis-weight: none` property on Vercel's side, the font starts to look rough like what I was referring to in my initial comment.

<img width="1659" alt="Screenshot 2024-05-09 at 20 34 47" src="https://github.com/sveltecult/franken-ui/assets/987814/4a0d54b6-7be7-43e1-97d2-d2a6b4ddb7fc">

**Comment by sveltecult** [comment]
This is docs-specific issue. Closing this for now.
